export const LANGUAGE_OPTIONS = [
  { label: 'C', value: 'c' },
  { label: 'C++', value: 'c++' },
  { label: 'C#', value: 'c#' },
  { label: 'Clojure', value: 'clojure' },
  { label: 'CMake', value: 'cmake' },
  { label: 'CSS', value: 'css' },
  { label: 'Dart', value: 'dart' },
  { label: 'Dockerfile', value: 'dockerfile' },
  { label: 'Elixir', value: 'elixir' },
  { label: 'Emacs Lisp', value: 'emacs lisp' },
  { label: 'Erlang', value: 'erlang' },
  { label: 'F#', value: 'f#' },
  { label: 'Go', value: 'go' },
  { label: 'Groovy', value: 'groovy' },
  { label: 'Haskell', value: 'haskell' },
  { label: 'HCL', value: 'hcl' },
  { label: 'HTML', value: 'html' },
  { label: 'Java', value: 'java' },
  { label: 'JavaScript', value: 'javascript' },
  { label: 'Jinja', value: 'jinja' },
  { label: 'JSON', value: 'json' },
  { label: 'Kotlin', value: 'kotlin' },
  { label: 'Lua', value: 'lua' },
  { label: 'Makefile', value: 'makefile' },
  { label: 'Nix', value: 'nix' },
  { label: 'Objective-C', value: 'objective-c' },
  { label: 'OCaml', value: 'ocaml' },
  { label: 'Perl', value: 'perl' },
  { label: 'PHP', value: 'php' },
  { label: 'PowerShell', value: 'powershell' },
  { label: 'Python', value: 'python' },
  { label: 'R', value: 'r' },
  { label: 'Ruby', value: 'ruby' },
  { label: 'Rust', value: 'rust' },
  { label: 'Scala', value: 'scala' },
  { label: 'SCSS', value: 'scss' },
  { label: 'Shell', value: 'shell' },
  { label: 'SQL', value: 'sql' },
  { label: 'Svelte', value: 'svelte' },
  { label: 'Swift', value: 'swift' },
  { label: 'TypeScript', value: 'typescript' },
  { label: 'Vim Script', value: 'vim script' },
  { label: 'Vue', value: 'vue' },
  { label: 'YAML', value: 'yaml' },
  { label: 'Zig', value: 'zig' },
] as const;

export const LABEL_OPTIONS = [
  { label: 'help wanted', value: 'help wanted' },
  { label: 'good first issue', value: 'good first issue' },
  { label: 'documentation', value: 'documentation' },
  { label: 'enhancement', value: 'enhancement' },
  { label: 'bug', value: 'bug' },
] as const;

export const SORT_OPTIONS = [
  { label: 'Newest', value: 'created' },
  { label: 'Recently Updated', value: 'updated' },
  { label: 'Most Commented', value: 'comments' },
] as const;
